declare module "*";
declare var isEnabled: boolean;
declare var googleAnalytics: any;
declare var ga: any;
declare var netflix: any;
declare var player: any;
declare var playerInstance: any;
declare var jwPlayer: any;
declare var currentLanguage: string;
declare var isLoaded: boolean;
declare var getPlayer: any;
declare var currentPath: string;
declare var subtitlesEnabled: boolean;
